import type { Invoice, Tenant, Proposal } from '@prisma/client';
import { formatCurrency } from '../utils';

interface ContentJson {
  lineItems?: { name: string; quantity: number; unitPrice: number; amount: number; hsn?: string }[];
  notes?: string;
}

export function renderInvoiceHtml(
  invoice: Invoice & { tenant: Tenant; proposal: Proposal | null }
): string {
  const t = invoice.tenant;
  const content = (invoice.contentJson ?? {}) as ContentJson;
  const lineItems = content.lineItems ?? [];
  const taxBlock = invoice.cgst + invoice.sgst > 0
    ? `<tr><td>CGST</td><td class="r">${formatCurrency(invoice.cgst, t.currency, t.locale)}</td></tr>
       <tr><td>SGST</td><td class="r">${formatCurrency(invoice.sgst, t.currency, t.locale)}</td></tr>`
    : `<tr><td>IGST</td><td class="r">${formatCurrency(invoice.igst, t.currency, t.locale)}</td></tr>`;
  return `<!doctype html>
<html><head><meta charset="utf-8" />
<title>Invoice ${invoice.number ?? invoice.id}</title>
<style>
body{font-family:ui-sans-serif,system-ui,sans-serif;padding:48px;color:#111;background:#fff;}
.header{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:16px;margin-bottom:32px}
.brand{font-size:20px;font-weight:700}
.muted{color:#666}
table{width:100%;border-collapse:collapse;margin-top:16px}
th,td{padding:8px 12px;border-bottom:1px solid #eee;text-align:left;font-size:14px}
th{background:#f6f6f8;font-weight:600;color:#333}
.r{text-align:right}
.total{font-size:20px;font-weight:700;margin-top:24px}
.badge{display:inline-block;padding:2px 8px;border-radius:999px;background:#f0f0f4;font-size:12px}
</style></head><body>
<div class="header">
  <div>
    <div class="brand">${escapeHtml(t.name)}</div>
    <div class="muted">${invoice.type === 'PROFORMA' ? 'Proforma Invoice' : 'Tax Invoice'}</div>
  </div>
  <div>
    <div class="muted">Invoice #</div>
    <div><strong>${invoice.number ?? '— (draft)'}</strong></div>
    <div class="muted" style="margin-top:8px">Date</div>
    <div>${invoice.issueDate.toISOString().slice(0,10)}</div>
  </div>
</div>
<table>
  <thead><tr><th>Item</th><th class="r">Qty</th><th class="r">Unit Price</th><th class="r">Amount</th></tr></thead>
  <tbody>
    ${lineItems.map((li) => `
      <tr>
        <td>${escapeHtml(li.name)}</td>
        <td class="r">${li.quantity}</td>
        <td class="r">${formatCurrency(li.unitPrice, t.currency, t.locale)}</td>
        <td class="r">${formatCurrency(li.amount, t.currency, t.locale)}</td>
      </tr>`).join('')}
  </tbody>
</table>
<table style="width:300px;margin-left:auto;margin-top:24px">
  <tr><td>Subtotal</td><td class="r">${formatCurrency(invoice.subtotal, t.currency, t.locale)}</td></tr>
  ${taxBlock}
  <tr><td class="total">Total</td><td class="r total">${formatCurrency(invoice.total, t.currency, t.locale)}</td></tr>
</table>
${invoice.irn ? `<p class="muted" style="margin-top:24px">IRN: <code>${invoice.irn}</code></p>` : ''}
${content.notes ? `<p style="margin-top:32px">${escapeHtml(content.notes)}</p>` : ''}
<p class="muted" style="margin-top:48px;font-size:12px">Generated by Avantus · Place of Supply: ${invoice.placeOfSupply}</p>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
}
